version: 2
jobs:
  docs-gen:
    description: "Generating documention"
    docker:
      - image: comerick/terminal:1.2
    steps:
      - checkout
      - run:
          name: Generate
          command: |
              mkdir docs
              cd docs/
              doxygen -g Doxyfile
              doxygen Doxyfile
              make html
      - persist_to_workspace:
        root: docs/_build
        paths: html
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
        at: docs/_build
      - add_ssh_keys:
            fingerprints:
              - "68:70:04:53:80:5f:60:c3:69:55:31:9b:69:69:44:b9"
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "groferik98@gmail.com"
            git config user.name "comerick"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/_build/html
  build_and_test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: g++ -std=c++11 main.cpp Directory.cpp Filesystem.cpp File.cpp
      - run: ./a.out < test.txt > output.txt
workflows:
  version: 2
  tasks:
    jobs:
      - build_and_test
      - docs-gen
      - docs-deploy:
          requires:
            - build_and_test
            - docs-gen
          filters:
            branches:
              only: master