version: 2
jobs:
  docs-gen:
    description: "Generating documention"
    docker:
      - image: comerick/terminal:1.2
    steps:
      - checkout
      - run:
          name: Generate
          command: |
              mkdir -p docs/_build
              cd docs/
              doxygen -g Doxyfile
              doxygen Doxyfile
              make html
      - persist_to_workspace:
          root: docs/_build
          paths: html
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
        name: Disable jekyll builds
        command: touch docs/_build/html/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "comerick11@gmail.com"
            git config user.name "comerick"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/_build/html
  build_and_test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: g++ -std=c++11 main.cpp Directory.cpp Filesystem.cpp File.cpp
      - run: ./a.out < test.txt > output.txt
workflows:
  version: 2
  tasks:
    jobs:
      - build_and_test
      - docs-gen
      - docs-deploy