
version: 2
jobs:
  build_and_test:
    docker:
      - image: comerick/tester:1.0
    steps:
      - checkout
      - run: 'make'
      - run: ./terminal < test.txt > output.txt
  doxygen:
    docker:
      - image: comerick/terminal:1.0
    steps:
      - checkout
      - run: doxygen Doxyfile
      - persist_to_workspace:
          root: docs/
          paths: 
            - latex
  saveDocs:
    docker:
      - image: comerick/tester:1.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/
      - run: 'cd docs/html && make'
      - run: ls docs/latex/
      - store_artifacts:
          path: docs/latex/refman.pdf
          destination: docs.pdf
workflows:
  version: 2
  tasks:
    jobs:
      - build_and_test
      - doxygen
      - saveDocs:
          requires:
            - doxygen
