
version: 2
jobs:
  build_and_test:
    docker:
      - image: comerick/tester:1.0
    steps:
      - checkout
      - run: 'make'
      - run: ./terminal < test.txt > output.txt
  doxygen:
    docker:
      - image: comerick/terminal:1.0
    steps:
      - checkout
      - run: 'doxygen Doxyfile && make -C docs/latex/.'
      - store_artifacts:
          path: docs/latex/refman.pdf
          destination: doc.pdf
workflows:
  version: 2
  tasks:
    jobs:
      - build_and_test
      - doxygen
