
version: 2
jobs:
  docs-deploy:
    docker:
      - image: comerick/doxydeploy:1.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/
      - add_ssh_keys:
          fingerprints:
            - "68:70:04:53:80:5f:60:c3:69:55:31:9b:69:69:44:b9"
      - run:
          name: Install and configure dependencies
          command: |
            git config user.email "groferik98@gmail.com"
            git config user.name "Comerick"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs/html
  build_and_test:
    docker:
      - image: comerick/tester:1.0
    steps:
      - checkout
      - run: 'make'
      - run: ./terminal < test.txt > output.txt
  doxygen:
    docker:
      - image: comerick/terminal:1.0
    steps:
      - checkout
      - run: doxygen Doxyfile
      - store_artifacts:
          path: docs/html
workflows:
  version: 2
  tasks:
    jobs:
      - build_and_test
      - doxygen
      - docs-deploy:
          requires:
            - build_and_test
            - doxygen
