
version: 2
jobs:
  doxygen:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Dependencies
          command: |
            sudo apt install doxygen
            sudo python3 -m pip install jinja2
      - run:
          name: Generate
          command: |
            mkdir docs
            cd docs
            doxygen Doxyfile
      - persist_to_workspace:
          paths:
            - xml
            - gh-pages
  build_and_test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: g++ -std=c++11 main.cpp Directory.cpp Filesystem.cpp File.cpp
      - run: ./a.out < test.txt > output.txt
workflows:
  version: 2
  tasks:
    jobs:
      - doxygen
      - build_and_test