
version: 2
jobs:
  docs-deploy:
    docker:
      - image: comerick/doxydeploy:1.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/
      - add_ssh_keys:
          fingerprints:
            - "eb:ad:48:a1:92:cc:b2:e6:8a:dd:76:a3:78:11:60:e5"
      - run:
          name: Install and configure dependencies
          command: |
            git config user.email "groferik98@gmail.com"
            git config user.name "Comerick"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs/html
  build_and_test:
    docker:
      - image: comerick/terminal:1.0
    steps:
      - checkout
      - run: g++ -std=c++11 main.cpp Directory.cpp Filesystem.cpp File.cpp
      - run: ./a.out < test.txt > output.txt
      - run: doxygen Doxyfile
      - persist_to_workspace:
          root: docs/
          paths: html
workflows:
  version: 2
  tasks:
    jobs:
      - build_and_test
      - docs-deploy:
          requires:
            - build_and_test
